// Agent registry — extracted from PromptForge.js (single source of truth)
// Last synced: 2026-03-28

export const PRO_INDUSTRIES = [
  'AI Agent Development',
  'Cyber Intelligence',
  'Cybersecurity',
  'Consulting & Strategy',
  'Architecture & Engineering',
  'SaaS & Product',
  'Banking & Lending',
  'Pharma & Biotech',
  'Aviation & Aerospace',
  'Executive & Leadership',
]

export const INDUSTRIES = {
  General: [
    { id: 'sop_gen', name: 'SOP Generator', desc: 'Upload any file → get a full Standard Operating Procedure' },
    { id: 'email_draft', name: 'Email Draft Agent', desc: 'Professional emails, cold outreach, follow-ups' },
    { id: 'cyber', name: 'Cybersecurity Advisor', desc: 'Threat assessment, security policies, incident response' },
    { id: 'code_review', name: 'Code Reviewer', desc: 'Security, performance, best practices' },
    { id: 'data', name: 'Data Analyst', desc: 'SQL, Python, insight generation' },
    { id: 'meeting_prep', name: 'Meeting Prep Agent', desc: 'Agenda drafting, talking points, follow-up summaries' },
    { id: 'pm', name: 'Project Manager', desc: 'Agile, risk, stakeholder comms' },
    { id: 'security', name: 'Security Assessor', desc: 'Risk analysis, vulnerability scans, security policies' },
    { id: 'finance', name: 'Financial Modeler', desc: 'Valuation, forecasting, scenario analysis, projections' },
    { id: 'market', name: 'Market Researcher', desc: 'Competitive intel, trend analysis' },
    { id: 'support', name: 'Customer Support', desc: 'De-escalation, resolution, empathy' },
    { id: 'content', name: 'Content Strategist', desc: 'SEO, brand voice, editorial calendar' },
    { id: 'devops', name: 'DevOps Engineer', desc: 'CI/CD, infra, incident response' },
    { id: 'pres_builder', name: 'Presentation Builder', desc: 'Slide outlines, speaker notes, deck structure' },
    { id: 'nego_strat', name: 'Negotiation Strategist', desc: 'BATNA analysis, counter-offers, leverage tactics' },
  ],
  Healthcare: [
    { id: 'med_scribe', name: 'Medical Scribe', desc: 'Clinical notes, EMR integration' },
    { id: 'prior_auth', name: 'Prior Auth Agent', desc: 'Payer workflows, claim denial reduction' },
    { id: 'rcm', name: 'RCM Specialist', desc: 'Billing, coding, A/R follow-ups' },
    { id: 'triage', name: 'Patient Triage Agent', desc: 'Symptom checking, care routing' },
    { id: 'diagnostics', name: 'Diagnostics Assistant', desc: 'Radiology & dermatology flagging' },
    { id: 'clinical_trial', name: 'Clinical Trial Coordinator', desc: 'Protocol summaries, consent forms, site reports' },
  ],
  Finance: [
    { id: 'close_agent', name: 'Autonomous Close Agent', desc: 'Financial close, multi-entity consolidation' },
    { id: 'treasury_liq', name: 'Treasury & Liquidity', desc: 'Cash forecasting, working capital mgmt' },
    { id: 'audit_comp', name: 'Audit & Compliance', desc: 'Fraud monitoring, regulatory drift' },
    { id: 'credit_risk', name: 'Credit Risk Underwriter', desc: 'Automated scoring, loan analysis' },
    { id: 'tax_agent', name: 'Tax Strategy Agent', desc: 'Real-time tax tracking, automated filing' },
    { id: 'fpa_analyst', name: 'FP&A Analyst', desc: 'Budget variance, rolling forecasts, board decks' },
  ],
  'Comms & Sales': [
    { id: 'sdr', name: 'Autonomous SDR', desc: 'Prospecting, outreach, lead qualification' },
    { id: 'repurpose', name: 'Content Repurposer', desc: 'One asset → 50+ social posts' },
    { id: 'voice_ai', name: 'Call Center Agent', desc: 'Call scripts, objection handling, appointment booking' },
    { id: 'market_intel', name: 'Market Intelligence', desc: 'Competitor pricing, strategic alerts' },
    { id: 'pr_agent', name: 'PR & Media Agent', desc: 'Journalist targeting, pitch drafting' },
    { id: 'proposal_gen', name: 'Proposal Generator', desc: 'Client proposals, scope docs, pricing sections' },
    { id: 'email_seq', name: 'Email Sequence Writer', desc: 'Drip campaigns, nurture flows, follow-up cadences' },
    { id: 'cust_success', name: 'Customer Success Agent', desc: 'Onboarding playbooks, churn prevention, QBR prep' },
  ],
  Education: [
    { id: 'micro_learn', name: 'Curriculum Designer', desc: 'Lesson plans, learning paths, assessment design' },
    { id: 'grading', name: 'Grading & Feedback', desc: 'Essays, coding critiques, instant feedback' },
    { id: 'career_track', name: 'Career Coach Agent', desc: 'Skills gap analysis, certification paths, job market intel' },
    { id: 'admissions', name: 'Admissions Agent', desc: 'Inquiry to enrollment pipeline mgmt' },
    { id: 'research_asst', name: 'Research Assistant', desc: 'Academic paper synthesis, doctoral support' },
    { id: 'parent_comm', name: 'Parent Communicator', desc: 'Progress reports, behavior updates, conference prep' },
    { id: 'grant_writer', name: 'Grant Writer', desc: 'Education grants, funding applications, budget narratives' },
  ],
  'Personal Finance': [
    { id: 'fin_advisor', name: 'Financial Advisor', desc: 'Full-context accounts, taxes, investments' },
    { id: 'sub_nego', name: 'Subscription Negotiator', desc: 'Find, cancel, renegotiate bills' },
    { id: 'tax_opt', name: 'Tax Optimizer', desc: 'Year-round deduction scanning' },
    { id: 'micro_invest', name: 'Investment Advisor', desc: 'Portfolio strategy, goal-based planning, risk allocation' },
    { id: 'fraud_watch', name: 'Identity Shield Agent', desc: 'Fraud detection, credit alerts, identity protection' },
    { id: 'budget_arch', name: 'Budget Architect', desc: 'Monthly budgets, expense tracking, savings goals' },
    { id: 'debt_payoff', name: 'Debt Payoff Strategist', desc: 'Payoff plans, refinance analysis, snowball vs avalanche' },
  ],
  Parenting: [
    { id: 'homework', name: 'Homework Helper', desc: 'Subject tutoring, step-by-step explanations' },
    { id: 'meal_plan', name: 'Family Meal Planner', desc: 'Weekly menus, grocery lists, dietary needs' },
    { id: 'development', name: 'Child Development Tracker', desc: 'Milestone tracking, age-appropriate guidance' },
    { id: 'stories', name: 'Bedtime Story Agent', desc: 'Custom stories, reading level adaptation' },
    { id: 'coach', name: 'Parent Coach', desc: 'Behavior strategies, emotional regulation' },
    { id: 'iep_advocate', name: 'IEP Advocate', desc: 'Special education plans, accommodation requests, meeting prep' },
  ],
  'Retail & Ops': [
    { id: 'inventory', name: 'Inventory Optimizer', desc: 'Demand forecasting, returns logistics' },
    { id: 'pricing_strat', name: 'Pricing Strategist', desc: 'Competitive pricing, margin analysis, discount modeling' },
    { id: 'supply_chain', name: 'Supply Chain Agent', desc: 'Bottleneck detection, re-routing' },
    { id: 'returns_agent', name: 'Returns & Refund Agent', desc: 'Return policies, customer resolution, loss prevention' },
    { id: 'vendor_nego', name: 'Vendor Negotiator', desc: 'Supplier terms, bulk pricing, contract leverage' },
    { id: 'store_ops', name: 'Store Operations Agent', desc: 'Staff scheduling, daily workflows, opening/closing checklists' },
  ],
  'Legal & Compliance': [
    { id: 'contract_analyze', name: 'Contract Analyzer', desc: 'Clause review, risk flagging, plain-language summaries' },
    { id: 'compliance_mon', name: 'Compliance Monitor', desc: 'Regulatory tracking, audit prep, policy gaps' },
    { id: 'policy_writer', name: 'Policy Writer', desc: 'Handbooks, privacy policies, internal procedures' },
    { id: 'reg_nav', name: 'Regulatory Navigator', desc: 'Licensing, filing deadlines, industry regulations' },
    { id: 'dispute_res', name: 'Dispute Resolution Agent', desc: 'Demand letters, mediation prep, escalation paths' },
    { id: 'ip_reviewer', name: 'IP Review Agent', desc: 'Patent search, trademark filings, infringement' },
  ],
  'Real Estate': [
    { id: 'listing_gen', name: 'Listing Generator', desc: 'Property descriptions, MLS optimization, photo captions' },
    { id: 'market_comp', name: 'Market Comp Analyzer', desc: 'Comparable sales, pricing strategy, market trends' },
    { id: 'lease_review', name: 'Lease Review Agent', desc: 'Clause analysis, tenant screening, renewal terms' },
    { id: 'lead_nurture', name: 'Lead Nurture Agent', desc: 'Follow-up sequences, client segmentation, drip campaigns' },
    { id: 'showing_sched', name: 'Showing Scheduler', desc: 'Appointment coordination, route planning, availability' },
    { id: 'open_house', name: 'Open House Agent', desc: 'Marketing flyers, follow-up scripts, social posts' },
  ],
  'Marketing & Growth': [
    { id: 'seo_content', name: 'SEO Content Agent', desc: 'Keyword strategy, content briefs, SERP analysis' },
    { id: 'campaign_opt', name: 'Campaign Optimizer', desc: 'Ad spend allocation, channel ROI, budget pacing' },
    { id: 'ab_analyst', name: 'A/B Test Analyst', desc: 'Experiment design, statistical significance, variant recs' },
    { id: 'brand_voice', name: 'Brand Voice Agent', desc: 'Tone guidelines, messaging frameworks, copy review' },
    { id: 'attrib_analyst', name: 'Attribution Analyst', desc: 'Multi-touch attribution, funnel analysis, conversion paths' },
    { id: 'social_mgr', name: 'Social Media Manager', desc: 'Content calendars, platform strategy, analytics reports' },
  ],
  'HR & People Ops': [
    { id: 'resume_screen', name: 'Resume Screener', desc: 'ATS filtering, candidate ranking, bias reduction' },
    { id: 'interview_arch', name: 'Interview Architect', desc: 'Role-specific questions, scoring rubrics, panel prep' },
    { id: 'onboard_agent', name: 'Onboarding Agent', desc: 'New hire workflows, checklist generation, 30-60-90 plans' },
    { id: 'comp_analyst', name: 'Compensation Analyst', desc: 'Salary benchmarking, equity modeling, offer structuring' },
    { id: 'perf_mgmt', name: 'Performance Manager', desc: 'Review cycles, goal tracking, feedback frameworks' },
    { id: 'employee_rel', name: 'Employee Relations Agent', desc: 'Investigations, grievance docs, PIP drafting' },
  ],
  'Accounting & Tax': [
    { id: 'bookkeeper', name: 'AI Bookkeeper', desc: 'Transaction categorization, reconciliation, cleanup' },
    { id: 'invoice_agent', name: 'Invoice Agent', desc: 'Invoice generation, payment tracking, aging reports' },
    { id: 'audit_prep', name: 'Audit Prep Agent', desc: 'Document assembly, compliance checks, gap analysis' },
    { id: 'tax_prep', name: 'Tax Prep Agent', desc: 'Deduction identification, filing checklists, deadlines' },
    { id: 'fin_reporter', name: 'Financial Reporter', desc: 'P&L statements, cash flow analysis, board reporting' },
    { id: 'payroll_spec', name: 'Payroll Specialist', desc: 'Payroll compliance, deduction calculations, reporting' },
  ],
  Insurance: [
    { id: 'claims_agent', name: 'Claims Processor', desc: 'Claim intake, documentation review, status tracking' },
    { id: 'underwrite', name: 'Underwriting Agent', desc: 'Risk assessment, policy pricing, coverage analysis' },
    { id: 'policy_comp', name: 'Policy Comparator', desc: 'Coverage comparison, gap identification, renewal analysis' },
    { id: 'ins_compliance', name: 'Insurance Compliance', desc: 'Regulatory filings, license tracking, audit readiness' },
    { id: 'client_intake', name: 'Client Intake Agent', desc: 'Needs assessment, quote generation, onboarding' },
    { id: 'renewal_spec', name: 'Renewal Specialist', desc: 'Renewal analysis, retention scripts, coverage updates' },
  ],
  'Architecture & Engineering': [
    { id: 'cost_est', name: 'Cost Estimator', desc: 'Quantity takeoffs, unit pricing, budget tracking' },
    { id: 'proj_coord', name: 'Project Coordinator', desc: 'Schedules, RFIs, submittals, stakeholder logs' },
    { id: 'rfi_drafter', name: 'RFI/RFP Drafter', desc: 'Submittals, clarifications, bid responses' },
    { id: 'site_report', name: 'Site Report Generator', desc: 'Inspection notes, punch lists, field reports' },
    { id: 'spec_review', name: 'Spec Review Agent', desc: 'CSI MasterFormat, IBC review, submittal QC' },
  ],
  'Consulting & Strategy': [
    { id: 'change_mgmt', name: 'Change Management Lead', desc: 'Stakeholder mapping, adoption plans, comms' },
    { id: 'due_diligence', name: 'Due Diligence Agent', desc: 'Risk assessment, deal analysis, investment memos' },
    { id: 'market_sizing', name: 'Market Sizing Analyst', desc: 'TAM/SAM/SOM, bottoms-up modeling' },
    { id: 'proposal_writer', name: 'Proposal & SOW Writer', desc: 'Scope, deliverables, pricing structure' },
    { id: 'strat_deck', name: 'Strategy Deck Builder', desc: 'Frameworks, slide structure, executive narratives' },
    { id: 'workshop_facil', name: 'Workshop Facilitator', desc: 'Agenda design, breakout exercises, Miro boards' },
  ],
  'Executive & Leadership': [
    { id: 'exec_brief', name: 'Executive Briefing Agent', desc: 'One-pagers, situation summaries, talking points' },
    { id: 'board_prep', name: 'Board Prep Agent', desc: 'Board decks, KPI narratives, governance docs' },
    { id: 'decision_frame', name: 'Decision Framework Agent', desc: 'Options analysis, risk matrices, go/no-go recs' },
    { id: 'exec_comms', name: 'Executive Comms Writer', desc: 'All-hands scripts, investor updates, memos' },
    { id: 'okr_agent', name: 'OKR & Goals Architect', desc: 'Objective cascading, alignment scoring, reviews' },
  ],
  'Hospitality & Events': [
    { id: 'event_plan', name: 'Event Planning Agent', desc: 'Timelines, vendor coordination, run-of-show docs' },
    { id: 'guest_exp', name: 'Guest Experience Agent', desc: 'Service scripts, complaint resolution, upselling' },
    { id: 'menu_eng', name: 'Menu Design Agent', desc: 'Pricing strategy, food cost analysis, descriptions' },
    { id: 'rev_mgmt', name: 'Revenue Management Agent', desc: 'Dynamic pricing, occupancy optimization, comp sets' },
    { id: 'staff_sched', name: 'Staff Scheduling Agent', desc: 'Shift coverage, labor cost forecasting, compliance' },
  ],
  'Logistics & Supply Chain': [
    { id: 'route_opt', name: 'Route Optimization Agent', desc: 'Fleet routing, delivery windows, fuel efficiency' },
    { id: 'warehouse_ops', name: 'Warehouse Ops Agent', desc: 'Layout optimization, pick/pack, labor' },
    { id: 'carrier_nego', name: 'Carrier Negotiation Agent', desc: 'Rate benchmarking, contract terms, lane analysis' },
    { id: 'customs_comp', name: 'Customs & Trade Agent', desc: 'HS codes, tariff classification, trade docs' },
    { id: 'demand_plan', name: 'Demand Planning Agent', desc: 'Forecast modeling, seasonality, SKU analysis' },
    { id: 'freight_audit', name: 'Freight Audit Agent', desc: 'Rate verification, invoice reconciliation, claims' },
  ],
  'Agriculture & Farming': [
    { id: 'ag_compliance', name: 'Ag Compliance Agent', desc: 'USDA reporting, organic certification, GAP audits' },
    { id: 'crop_plan', name: 'Crop Planning Agent', desc: 'Rotation scheduling, seed selection, yield forecasting' },
    { id: 'farm_finance', name: 'Farm Financial Agent', desc: 'FSA loan applications, crop insurance, cash flow' },
    { id: 'livestock_mgmt', name: 'Livestock Manager', desc: 'Herd records, breeding schedules, feed optimization' },
    { id: 'precision_ag', name: 'Precision Ag Agent', desc: 'Variable-rate application, soil mapping, drone data' },
  ],
  Automotive: [
    { id: 'dealer_crm', name: 'Dealer CRM Agent', desc: 'Lead scoring, follow-up cadence, BDC scripts' },
    { id: 'parts_mgmt', name: 'Parts Inventory Agent', desc: 'Reorder points, obsolescence tracking, core returns' },
    { id: 'service_advisor', name: 'Service Advisor Agent', desc: 'Repair estimates, upsell recommendations, DVI reports' },
    { id: 'vehicle_appr', name: 'Vehicle Appraisal Agent', desc: 'Trade-in valuation, market comps, condition grading' },
    { id: 'warranty_agent', name: 'Warranty Claims Agent', desc: 'OEM submission, labor time guides, parts markup' },
  ],
  'Aviation & Aerospace': [
    { id: 'aero_cert', name: 'Certification Agent', desc: 'FAA/EASA compliance, type certification, STC apps' },
    { id: 'flight_ops', name: 'Flight Operations Agent', desc: 'Dispatch planning, fuel optimization, MEL management' },
    { id: 'ground_ops', name: 'Ground Operations Agent', desc: 'Turnaround optimization, gate assignments, crew' },
    { id: 'mro_agent', name: 'MRO Planning Agent', desc: 'Airworthiness directives, C-check scheduling, parts' },
    { id: 'safety_mgmt', name: 'Aviation Safety Agent', desc: 'SMS compliance, hazard reporting, risk matrices' },
  ],
  'Banking & Lending': [
    { id: 'branch_ops', name: 'Branch Operations Agent', desc: 'Teller workflows, cross-sell scripts, compliance' },
    { id: 'comm_lender', name: 'Commercial Lending Agent', desc: 'Term sheets, covenant analysis, credit memos' },
    { id: 'kyc_agent', name: 'KYC/AML Agent', desc: 'Identity verification, risk profiling, SAR drafting' },
    { id: 'loan_orig', name: 'Loan Origination Agent', desc: 'Application review, DTI analysis, disclosure prep' },
    { id: 'portfolio_mgr', name: 'Portfolio Manager Agent', desc: 'Asset allocation, rebalancing, performance attribution' },
    { id: 'deposit_ops', name: 'Deposit Operations Agent', desc: 'Reg CC holds, exception processing, account QC' },
  ],
  'Construction & Trades': [
    { id: 'bid_est', name: 'Bid Estimator', desc: 'Material takeoffs, labor costing, markup strategy' },
    { id: 'inspect_agent', name: 'Inspection Agent', desc: 'Punch lists, code violations, photo documentation' },
    { id: 'material_calc', name: 'Material Calculator', desc: 'Quantity estimation, waste factors, supplier quotes' },
    { id: 'safety_comp', name: 'Safety Compliance Agent', desc: 'OSHA standards, toolbox talks, incident reporting' },
    { id: 'sched_opt', name: 'Schedule Optimizer', desc: 'Critical path, Gantt sequencing, weather delays' },
  ],
  Cybersecurity: [
    { id: 'incident_resp', name: 'Incident Response Agent', desc: 'NIST IR framework, containment, forensic triage' },
    { id: 'pentest_plan', name: 'Pentest Planner', desc: 'OWASP methodology, scope, rules of engagement' },
    { id: 'soc_analyst', name: 'SOC Analyst Agent', desc: 'SIEM triage, alert correlation, MITRE ATT&CK' },
    { id: 'threat_model', name: 'Threat Modeling Agent', desc: 'STRIDE analysis, attack surfaces, risk scoring' },
    { id: 'vuln_mgmt', name: 'Vulnerability Manager', desc: 'CVE prioritization, CVSS scoring, patch cycles' },
    { id: 'grc_analyst', name: 'GRC Analyst', desc: 'Risk registers, NIST CSF mapping, audit evidence' },
  ],
  'Dental & Optometry': [
    { id: 'dental_treatment', name: 'Treatment Plan Agent', desc: 'Procedure sequencing, insurance coding, patient education' },
    { id: 'ins_verify', name: 'Insurance Verification Agent', desc: 'Eligibility checks, pre-auth coding, benefits breakdown' },
    { id: 'optical_sales', name: 'Optical Sales Agent', desc: 'Frame selection, lens upselling, insurance benefits' },
    { id: 'patient_comms', name: 'Patient Communications Agent', desc: 'Appointment reminders, post-op instructions, recalls' },
    { id: 'practice_mgmt', name: 'Practice Manager Agent', desc: 'Chair utilization, recall scheduling, KPI dashboards' },
  ],
  'E-commerce & DTC': [
    { id: 'abandon_cart', name: 'Cart Recovery Agent', desc: 'Abandonment flows, urgency copy, retargeting' },
    { id: 'listing_opt', name: 'Listing Optimizer', desc: 'SEO titles, A+ content, keyword optimization' },
    { id: 'pricing_intel', name: 'Pricing Intelligence Agent', desc: 'Competitor monitoring, margin analysis, dynamic pricing' },
    { id: 'product_desc', name: 'Product Description Agent', desc: 'Feature-benefit copy, brand voice, A/B variants' },
    { id: 'review_mgmt', name: 'Review Management Agent', desc: 'Response templates, sentiment analysis, UGC strategy' },
    { id: 'ecomm_email', name: 'Email Marketing Agent', desc: 'Klaviyo flows, segmentation, lifecycle campaigns' },
  ],
  'Energy & Utilities': [
    { id: 'energy_audit', name: 'Energy Audit Agent', desc: 'Consumption analysis, retrofit ROI, ASHRAE standards' },
    { id: 'field_service', name: 'Field Service Agent', desc: 'Work order routing, safety protocols, crew scheduling' },
    { id: 'grid_ops', name: 'Grid Operations Agent', desc: 'Load forecasting, outage management, SCADA monitoring' },
    { id: 'renew_dev', name: 'Renewable Development Agent', desc: 'PPA negotiation, interconnection apps, site assessment' },
    { id: 'util_reg', name: 'Utility Regulatory Agent', desc: 'Rate case filings, FERC compliance, tariff analysis' },
    { id: 'renew_finance', name: 'Renewable Finance Agent', desc: 'PPA modeling, ITC/PTC analysis, project finance' },
  ],
  'Fitness & Wellness': [
    { id: 'class_sched', name: 'Class Schedule Agent', desc: 'Time slot optimization, instructor allocation' },
    { id: 'client_progress', name: 'Client Progress Agent', desc: 'Body comp tracking, milestone analysis, program adjustments' },
    { id: 'nutrition_plan', name: 'Nutrition Planning Agent', desc: 'Macro calculations, meal prep, dietary restrictions' },
    { id: 'program_design', name: 'Program Design Agent', desc: 'Periodization, progressive overload, exercise selection' },
    { id: 'wellness_coach', name: 'Wellness Coach Agent', desc: 'Stress management, sleep protocols, habit formation' },
  ],
  'Freelancers & Solopreneurs': [
    { id: 'client_onboard', name: 'Client Onboarding Agent', desc: 'Welcome packets, kickoff agendas, milestone plans' },
    { id: 'freelance_pitch', name: 'Freelance Pitch Writer', desc: 'Platform proposals, cold outreach, portfolio framing' },
    { id: 'portfolio_build', name: 'Portfolio Builder', desc: 'Case studies, project narratives, testimonial framing' },
    { id: 'rate_calc', name: 'Rate & Pricing Agent', desc: 'Value-based pricing, rate cards, project scoping' },
    { id: 'scope_guard', name: 'Scope Guard Agent', desc: 'Scope creep detection, change orders, boundary setting' },
  ],
  Manufacturing: [
    { id: 'lean_agent', name: 'Lean Manufacturing Agent', desc: 'Kaizen events, value stream mapping, 5S audits' },
    { id: 'maint_plan', name: 'Maintenance Planner', desc: 'PM schedules, CMMS workflows, MTBF analysis' },
    { id: 'proc_agent', name: 'Procurement Agent', desc: 'RFQ drafting, vendor scoring, contract negotiation' },
    { id: 'prod_sched', name: 'Production Scheduler', desc: 'MRP planning, capacity balancing, downtime scheduling' },
    { id: 'quality_ctrl', name: 'Quality Control Agent', desc: 'Six Sigma, SPC charts, defect root cause analysis' },
    { id: 'ehs_agent', name: 'EHS Compliance Agent', desc: 'ISO 14001, OSHA recordkeeping, incident reports' },
  ],
  'Media & Publishing': [
    { id: 'audience_dev', name: 'Audience Development Agent', desc: 'Growth tactics, newsletter optimization, paywall strategy' },
    { id: 'content_cal', name: 'Content Calendar Agent', desc: 'Editorial planning, deadline tracking, cross-platform' },
    { id: 'copy_editor', name: 'Copy Editor Agent', desc: 'AP/Chicago style, fact-checking, headline optimization' },
    { id: 'editorial_agent', name: 'Editorial Agent', desc: 'Story pitching, angle development, source identification' },
    { id: 'rights_mgmt', name: 'Rights & Licensing Agent', desc: 'Syndication terms, copyright clearance, usage tracking' },
  ],
  'Nonprofit & Government': [
    { id: 'constituent_svc', name: 'Constituent Service Agent', desc: 'Case management, response templates, escalation' },
    { id: 'ngo_grant_writer', name: 'Grant Writer Agent', desc: 'LOI drafting, narrative structure, budget justification' },
    { id: 'impact_report', name: 'Impact Report Generator', desc: 'Logic models, outcome metrics, donor storytelling' },
    { id: 'policy_analyst', name: 'Policy Analyst Agent', desc: 'Legislative tracking, regulatory impact, public comment' },
    { id: 'volunteer_coord', name: 'Volunteer Coordinator', desc: 'Shift scheduling, onboarding, recognition programs' },
  ],
  'Pharma & Biotech': [
    { id: 'clin_trial', name: 'Clinical Trial Agent', desc: 'Protocol design, ICH-GCP compliance, site selection' },
    { id: 'drug_safety', name: 'Drug Safety Agent', desc: 'Pharmacovigilance, ICSR reporting, signal detection' },
    { id: 'med_affairs', name: 'Medical Affairs Agent', desc: 'KOL engagement, MSL briefings, publication planning' },
    { id: 'pharma_qc', name: 'Pharma QA/QC Agent', desc: 'GMP compliance, batch records, deviation handling' },
    { id: 'reg_submit', name: 'Regulatory Submission Agent', desc: 'FDA 510(k), IND applications, CTD formatting' },
  ],
  'Property Management': [
    { id: 'lease_mgmt', name: 'Lease Management Agent', desc: 'Renewal terms, rent escalation, clause negotiation' },
    { id: 'maint_coord', name: 'Maintenance Coordinator', desc: 'Work orders, vendor dispatch, preventive schedules' },
    { id: 'prop_financials', name: 'Property Financials Agent', desc: 'NOI analysis, cap rate modeling, expense forecasting' },
    { id: 'tenant_comms', name: 'Tenant Communications Agent', desc: 'Notice drafting, policy updates, community management' },
    { id: 'tenant_screen', name: 'Tenant Screening Agent', desc: 'Background checks, income verification, risk scoring' },
  ],
  'Recruitment & Staffing': [
    { id: 'employer_brand', name: 'Employer Brand Agent', desc: 'EVP messaging, careers page copy, Glassdoor strategy' },
    { id: 'job_desc', name: 'Job Description Writer', desc: 'Role scoping, inclusive language, SEO-optimized' },
    { id: 'offer_letter', name: 'Offer Letter Agent', desc: 'Comp packaging, equity terms, closing language' },
    { id: 'recruit_pipe', name: 'Recruiting Pipeline Agent', desc: 'Pipeline metrics, candidate scoring, SLA tracking' },
    { id: 'source_agent', name: 'Sourcing Agent', desc: 'Boolean search, talent mapping, outreach sequences' },
    { id: 'contingent_mgmt', name: 'Contingent Workforce Agent', desc: 'Contractor compliance, rate cards, SOW drafting' },
  ],
  'SaaS & Product': [
    { id: 'churn_analyst', name: 'Churn Analyst', desc: 'Cohort analysis, retention modeling, win-back flows' },
    { id: 'feature_prior', name: 'Feature Prioritization Agent', desc: 'RICE scoring, impact mapping, roadmap sequencing' },
    { id: 'prd_writer', name: 'PRD Writer', desc: 'User stories, acceptance criteria, spec drafting' },
    { id: 'release_notes', name: 'Release Notes Writer', desc: 'Changelogs, feature announcements, migration guides' },
    { id: 'user_research', name: 'User Research Agent', desc: 'Interview scripts, survey design, insight synthesis' },
    { id: 'onboard_flow', name: 'Onboarding Flow Designer', desc: 'Activation metrics, user journeys, tooltip copy' },
  ],
  'Sports & Athletics': [
    { id: 'athlete_perf', name: 'Athlete Performance Agent', desc: 'Training load, recovery protocols, biomechanics' },
    { id: 'fan_engage', name: 'Fan Engagement Agent', desc: 'Social campaigns, merchandise strategy, loyalty programs' },
    { id: 'game_plan', name: 'Game Plan Agent', desc: 'Formation analysis, tendency reports, situational play' },
    { id: 'scout_analyst', name: 'Scouting Analyst', desc: 'Player evaluation, combine metrics, draft modeling' },
    { id: 'sports_ops', name: 'Sports Operations Agent', desc: 'Event logistics, facility scheduling, contract management' },
  ],
  Veterinary: [
    { id: 'pet_comms', name: 'Pet Owner Communications', desc: 'Discharge instructions, recall reminders, wellness tips' },
    { id: 'practice_growth', name: 'Practice Growth Agent', desc: 'Client acquisition, retention metrics, service expansion' },
    { id: 'vet_billing', name: 'Veterinary Billing Agent', desc: 'Procedure coding, estimate generation, payment plans' },
    { id: 'vet_records', name: 'Veterinary Records Agent', desc: 'SOAP notes, treatment plans, vaccination schedules' },
    { id: 'vet_triage', name: 'Veterinary Triage Agent', desc: 'Symptom assessment, urgency classification, referral' },
  ],
  'AI Agent Development': [
    { id: 'agent_arch', name: 'Agent Architecture Designer', desc: 'Multi-agent systems, tool use, orchestration' },
    { id: 'tool_builder', name: 'Tool Use Designer', desc: 'Function calling, MCP servers, tool schemas' },
    { id: 'eval_agent', name: 'Prompt Evaluation Agent', desc: 'Eval frameworks, benchmarks, quality scoring' },
    { id: 'multi_orch', name: 'Multi-Agent Orchestrator', desc: 'Task queues, handoff protocols, shared state' },
    { id: 'soul_writer', name: 'SOUL.md Writer', desc: 'Personality design, behavioral boundaries, tone' },
    { id: 'memory_arch', name: 'Agent Memory Architect', desc: 'Context management, compaction, MEMORY.md design' },
    { id: 'skill_builder', name: 'AgentSkill Builder', desc: 'SKILL.md creation, frontmatter, tool integration' },
    { id: 'openclaw_deploy', name: 'OpenClaw Deployment Agent', desc: 'SOUL.md, AGENTS.md, Gateway config, channel setup' },
    { id: 'agent_sec', name: 'Agent Security Auditor', desc: 'Prompt injection, data exfiltration, permissions' },
    { id: 'agent_test', name: 'Agent Testing Strategist', desc: 'Scenario coverage, edge cases, regression testing' },
  ],
  'Cyber Intelligence': [
    { id: 'osint_planner', name: 'OSINT Investigation Planner', desc: 'Investigation workflows, OPSEC, evidence chain' },
    { id: 'digi_footprint', name: 'Digital Footprint Analyst', desc: 'OSINT mapping, Maltego, Shodan, public records' },
    { id: 'threat_intel', name: 'Threat Intelligence Analyst', desc: 'MITRE ATT&CK, Diamond Model, Kill Chain, TTPs' },
    { id: 'cred_exposure', name: 'Credential Exposure Monitor', desc: 'Breach scanning, API key leaks, GitHub dorking' },
    { id: 'domain_recon', name: 'Domain & Infrastructure Recon', desc: 'DNS recon, subdomain enumeration, SSL analysis' },
    { id: 'darkweb_mon', name: 'Dark Web Monitor', desc: 'Threat actor tracking, leak monitoring, MISP' },
    { id: 'socmedia_intel', name: 'Social Media Intelligence', desc: 'SOCMINT, sentiment analysis, network mapping' },
    { id: 'corp_dd', name: 'Corporate Due Diligence Agent', desc: 'EDGAR filings, UBO registries, court records' },
    { id: 'disinfo_analyst', name: 'Disinformation Analyst', desc: 'Bot detection, deepfake analysis, IO tracking' },
    { id: 'geoloc_intel', name: 'Geolocation Intelligence', desc: 'GEOINT, EXIF analysis, satellite imagery, SunCalc' },
  ],
}
